dist: trusty
sudo: false

addons:
  apt:
    packages:
      - libsdl2-2.0-0

language: python

python:
  - '3.6'
  - '3.6-dev' # 3.6 development branch
  - 'nightly' # currently points to 3.7-dev

git:
  depth: 3

before_install:
  - "export TRAVIS_COMMIT_MSG=\"$(git log --format=%f --no-merges -n 1)\""
  - bash ./travis_deploy.sh

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - python setup.py install

script:
  - python setup.py clean --all
  - py3clean .
  - coverage run --source=vulk --omit="vulk/tests*" setup.py test
  - flake8 vulk
  - pylint --rcfile=.pylintrc-travis vulk

after_success:
  - coveralls

deploy:
  provider: script
  script: 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./travis_deploy.sh; fi'
  on:
    python: '3.6'

matrix:
  allow_failures:
    - python: '3.6-dev'
    - python: 'nightly'
